#!/usr/bin/env python3
"""
ollama-md.py — Local-model Markdown worker for SpecKit Pro.

One invocation = one artifact. Wraps the Ollama HTTP chat API
(http://localhost:11434/api/chat) with a strict "produce Markdown, mark
UNKNOWN, do not invent facts" system prompt. Designed to be called from
bash drivers (pro-local-prep.sh, pro-local-review.sh, pro-materialize.sh).

Usage:
  ollama-md.py --model <name> --prompt-file <path> --out-file <path>
               [--system-file <path>]
               [--context-file <path>]...
               [--base-url http://localhost:11434]
               [--timeout 180]
               [--temperature 0.2]
               [--num-ctx 8192]
               [--banner "..."]
               [--task <task-name>]
               [--feature <feature-slug>]
               [--metrics-file <path>]
               [--quiet]

Exit codes:
  0 — success, artifact written
  2 — Ollama unreachable (server not running / wrong URL)
  3 — Ollama returned an error (model not pulled, bad payload)
  4 — request timed out
  1 — bad CLI input / I/O error

The output file is overwritten. A short provenance banner is prepended
unless --banner "" is passed explicitly.

Metrics (layer 1 telemetry): when --metrics-file is provided, ONE JSONL
line is appended on EVERY exit path (success or failure). Schema:

  {"type":"call","ts":"...Z","feature":"...","task":"...","model":"...",
   "num_ctx":8192,"temperature":0.2,"timeout_s":180,"prompt_bytes":N,
   "output_bytes":N,"wall_ms":N,"exit_code":N,"error":null|"..."}

The bash drivers compute --metrics-file as
<PROJECT_ROOT>/.ai-knowledge/local-metrics.jsonl so all features
aggregate to one file (`.ai-knowledge/` is gitignored workspace state).
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import socket
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

DEFAULT_SYSTEM_PROMPT = (
    "You are a local Markdown worker for SpecKit Pro. "
    "Produce concise, structured Markdown only. "
    "Use the exact section headings the user requests. "
    "If a fact is not present in the supplied context, write UNKNOWN — "
    "never invent file paths, function names, line numbers, or API names. "
    "Do not write code blocks unless explicitly asked. "
    "Do not add a preamble, sign-off, or meta-commentary. "
    "Output begins at the first H1 heading the user prompt specifies."
)

DEFAULT_BANNER = (
    "> _Generated by local model `{model}` via `ollama-md.py`. "
    "Claims require verification before implementation._\n\n"
)


class OllamaError(Exception):
    """Raised when the Ollama call cannot be completed.

    `code` maps to the process exit code we want main() to use.
    """

    def __init__(self, code: int, message: str):
        super().__init__(message)
        self.code = code


def _read_text(path: str) -> str:
    return Path(path).read_text(encoding="utf-8")


def _build_user_content(prompt_text: str, context_files: list[str]) -> str:
    if not context_files:
        return prompt_text
    parts: list[str] = ["## CONTEXT", ""]
    for ctx_path in context_files:
        label = Path(ctx_path).name
        parts.append(f"### {label}")
        parts.append("```")
        try:
            parts.append(_read_text(ctx_path).rstrip())
        except OSError as exc:
            parts.append(f"<could not read {ctx_path}: {exc}>")
        parts.append("```")
        parts.append("")
    parts.append("## INSTRUCTIONS")
    parts.append("")
    parts.append(prompt_text)
    return "\n".join(parts)


def _call_ollama(
    base_url: str,
    model: str,
    system_prompt: str,
    user_content: str,
    timeout: int,
    temperature: float,
    num_ctx: int,
) -> str:
    """Call Ollama. Raises OllamaError on any failure with the right exit code."""
    payload = {
        "model": model,
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_ctx": num_ctx,
        },
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ],
    }
    url = base_url.rstrip("/") + "/api/chat"
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace") if exc.fp else str(exc)
        raise OllamaError(3, f"HTTP {exc.code} from {url}: {detail[:500]}")
    except urllib.error.URLError as exc:
        reason = getattr(exc, "reason", exc)
        if isinstance(reason, (ConnectionRefusedError, socket.gaierror)):
            raise OllamaError(
                2,
                f"Ollama not reachable at {url} ({reason}). "
                "Start it with `ollama serve`, or set local_models.enabled: false.",
            )
        if isinstance(reason, socket.timeout):
            raise OllamaError(4, f"Timed out after {timeout}s talking to {url}.")
        raise OllamaError(2, f"URLError contacting {url}: {reason}")
    except socket.timeout:
        raise OllamaError(4, f"Timed out after {timeout}s talking to {url}.")

    try:
        data = json.loads(body)
    except json.JSONDecodeError as exc:
        raise OllamaError(3, f"Could not parse Ollama response: {exc}\n{body[:500]}")

    if "error" in data:
        raise OllamaError(3, f"Ollama error: {data['error']}")

    msg = data.get("message") or {}
    content = msg.get("content")
    if not content:
        raise OllamaError(3, "Ollama returned no message content.")
    return content


def _infer_feature_from_out(out_path: str) -> str:
    """Best-effort feature slug from the out-file path.

    Matches `…/specs/<slug>/…` first; falls back to the immediate parent
    directory's name. Used only when --feature is not provided.
    """
    m = re.search(r"/specs/([^/]+)/", out_path.replace("\\", "/"))
    if m:
        return m.group(1)
    # Walk up looking for a name not in {local-reviews, task-packets}
    p = Path(out_path).resolve()
    for ancestor in p.parents:
        name = ancestor.name
        if name and name not in {"local-reviews", "task-packets", "contracts", "evaluations"}:
            return name
    return ""


def _emit_metrics(
    metrics_file: str | None,
    *,
    task: str,
    feature: str,
    model: str,
    num_ctx: int,
    temperature: float,
    timeout_s: int,
    prompt_bytes: int,
    output_bytes: int,
    wall_ms: int,
    exit_code: int,
    error: str | None,
) -> None:
    """Append one JSONL line to `metrics_file`. Silent on any I/O error —
    telemetry must never break a user-facing run.
    """
    if not metrics_file:
        return
    record = {
        "type": "call",
        "ts": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "feature": feature or "",
        "task": task or "",
        "model": model,
        "num_ctx": num_ctx,
        "temperature": temperature,
        "timeout_s": timeout_s,
        "prompt_bytes": prompt_bytes,
        "output_bytes": output_bytes,
        "wall_ms": wall_ms,
        "exit_code": exit_code,
        "error": error,
    }
    try:
        path = Path(metrics_file)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(record, separators=(",", ":")) + "\n")
    except OSError:
        # Never let telemetry failures bubble up.
        pass


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render a Markdown artifact via Ollama for SpecKit Pro."
    )
    parser.add_argument("--model", required=True)
    parser.add_argument("--prompt-file", required=True)
    parser.add_argument("--out-file", required=True)
    parser.add_argument("--system-file", default=None)
    parser.add_argument(
        "--context-file",
        action="append",
        default=[],
        help="May be repeated; each file is wrapped in a fenced block under ## CONTEXT.",
    )
    parser.add_argument(
        "--base-url",
        default=os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434"),
    )
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--temperature", type=float, default=0.2)
    parser.add_argument(
        "--num-ctx",
        type=int,
        default=8192,
        help="Context window tokens passed to Ollama (model-dependent).",
    )
    parser.add_argument(
        "--banner",
        default=None,
        help='Provenance banner prepended to the output. Pass "" to disable.',
    )
    parser.add_argument(
        "--task",
        default="",
        help="Logical task name for telemetry (e.g. repo-map, security-review).",
    )
    parser.add_argument(
        "--feature",
        default="",
        help="Feature slug for telemetry. Inferred from --out-file if omitted.",
    )
    parser.add_argument(
        "--metrics-file",
        default=os.environ.get("SPECKIT_PRO_METRICS_FILE", ""),
        help="JSONL file to append one telemetry line to. Empty disables telemetry.",
    )
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    feature = args.feature or _infer_feature_from_out(args.out_file)
    metrics_file = args.metrics_file or None

    # ── Load prompt ──────────────────────────────────────────────────────────
    try:
        prompt_text = _read_text(args.prompt_file)
    except OSError as exc:
        msg = f"Could not read prompt file {args.prompt_file}: {exc}"
        print(f"[ollama-md] {msg}", file=sys.stderr)
        _emit_metrics(
            metrics_file, task=args.task, feature=feature, model=args.model,
            num_ctx=args.num_ctx, temperature=args.temperature, timeout_s=args.timeout,
            prompt_bytes=0, output_bytes=0, wall_ms=0, exit_code=1, error=msg,
        )
        return 1

    system_prompt = DEFAULT_SYSTEM_PROMPT
    if args.system_file:
        try:
            system_prompt = _read_text(args.system_file)
        except OSError as exc:
            msg = f"Could not read system file: {exc}"
            print(f"[ollama-md] {msg}", file=sys.stderr)
            _emit_metrics(
                metrics_file, task=args.task, feature=feature, model=args.model,
                num_ctx=args.num_ctx, temperature=args.temperature, timeout_s=args.timeout,
                prompt_bytes=0, output_bytes=0, wall_ms=0, exit_code=1, error=msg,
            )
            return 1

    user_content = _build_user_content(prompt_text, args.context_file)
    prompt_bytes = len(user_content.encode("utf-8"))

    out_path = Path(args.out_file)
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        msg = f"Could not create output directory: {exc}"
        print(f"[ollama-md] {msg}", file=sys.stderr)
        _emit_metrics(
            metrics_file, task=args.task, feature=feature, model=args.model,
            num_ctx=args.num_ctx, temperature=args.temperature, timeout_s=args.timeout,
            prompt_bytes=prompt_bytes, output_bytes=0, wall_ms=0, exit_code=1, error=msg,
        )
        return 1

    started = time.time()
    if not args.quiet:
        print(
            f"[ollama-md] {args.model} → {out_path.name} "
            f"(ctx={args.num_ctx}, t={args.temperature}, timeout={args.timeout}s)",
            file=sys.stderr,
        )

    # ── Call Ollama ──────────────────────────────────────────────────────────
    try:
        content = _call_ollama(
            base_url=args.base_url,
            model=args.model,
            system_prompt=system_prompt,
            user_content=user_content,
            timeout=args.timeout,
            temperature=args.temperature,
            num_ctx=args.num_ctx,
        )
    except OllamaError as exc:
        wall_ms = int((time.time() - started) * 1000)
        print(f"[ollama-md] {exc}", file=sys.stderr)
        _emit_metrics(
            metrics_file, task=args.task, feature=feature, model=args.model,
            num_ctx=args.num_ctx, temperature=args.temperature, timeout_s=args.timeout,
            prompt_bytes=prompt_bytes, output_bytes=0, wall_ms=wall_ms,
            exit_code=exc.code, error=str(exc),
        )
        return exc.code

    # ── Write output ─────────────────────────────────────────────────────────
    banner = DEFAULT_BANNER.format(model=args.model) if args.banner is None else args.banner
    final = banner + content.strip() + "\n"
    output_bytes = len(final.encode("utf-8"))
    try:
        out_path.write_text(final, encoding="utf-8")
    except OSError as exc:
        wall_ms = int((time.time() - started) * 1000)
        msg = f"Could not write {out_path}: {exc}"
        print(f"[ollama-md] {msg}", file=sys.stderr)
        _emit_metrics(
            metrics_file, task=args.task, feature=feature, model=args.model,
            num_ctx=args.num_ctx, temperature=args.temperature, timeout_s=args.timeout,
            prompt_bytes=prompt_bytes, output_bytes=0, wall_ms=wall_ms,
            exit_code=1, error=msg,
        )
        return 1

    wall_ms = int((time.time() - started) * 1000)
    if not args.quiet:
        print(
            f"[ollama-md] wrote {out_path} ({output_bytes} bytes, {wall_ms/1000:.1f}s)",
            file=sys.stderr,
        )
    _emit_metrics(
        metrics_file, task=args.task, feature=feature, model=args.model,
        num_ctx=args.num_ctx, temperature=args.temperature, timeout_s=args.timeout,
        prompt_bytes=prompt_bytes, output_bytes=output_bytes, wall_ms=wall_ms,
        exit_code=0, error=None,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
