#!/usr/bin/env python3
"""scan_report.py — assemble the merged scan report + Coverage Ledger.

The *findings* sections (architecture / dependency / risk / conflicts) are
produced by the LLM merge stage (templates/scan/merge.prompt.md) and passed in
via --findings-md. THIS script owns the deterministic, safety-critical parts:

  - the Coverage Ledger — one row per leaf portion, sourced from the per-portion
    result files; a portion with no result file is recorded as `failed` with a
    reason. This is what guarantees NO SILENT GAPS (FR-010, FR-018).
  - atomic, race-safe output (FR-008, SC-005, task T035): write latest.md via
    temp-file + os.replace under a per-repo lock, plus a timestamped archive.

Stdlib only. See report-format.md + data-model.md (Coverage Ledger).
"""
import argparse
import json
import os
import sys
import time

VALID_STATUS = {"complete", "summarized", "failed", "truncated"}


def load_portions(path):
    doc = json.load(open(path, encoding="utf-8"))
    return doc.get("portions", doc if isinstance(doc, list) else [])


def portion_status(results_dir, portion_id):
    """(status, reason) for one portion, derived from its result file."""
    rf = os.path.join(results_dir, portion_id + ".json")
    if not os.path.isfile(rf):
        return "failed", "no result file (worker did not report)"
    try:
        r = json.load(open(rf, encoding="utf-8"))
    except (OSError, ValueError) as e:
        return "failed", "unreadable result (%s)" % e
    st = r.get("status", "failed")
    if st not in VALID_STATUS:
        return "failed", "invalid status %r" % st
    if st == "complete":
        return "analyzed", ""
    if st == "summarized":
        return "summarized", r.get("error") or "exceeded worker budget"
    return st, r.get("error") or st  # failed / truncated need a reason


def coverage_ledger(portions, results_dir):
    rows, gaps = [], 0
    for p in portions:
        pid = p["portion_id"]
        st, reason = portion_status(results_dir, pid)
        if st != "analyzed":
            gaps += 1
        rows.append({"portion": pid, "files": len(p.get("files", [])),
                     "status": st, "reason": reason or "—"})
    return rows, gaps


def render(meta, findings_md, ledger_rows, capped):
    L = []
    L.append("# Scan Report — %s" % meta.get("repo", "repository"))
    L.append("")
    speed = ""
    if meta.get("wall_ms") and meta.get("baseline_ms"):
        try:
            speed = " | speedup: %.1fx" % (meta["baseline_ms"] / max(1, meta["wall_ms"]))
        except Exception:
            speed = ""
    L.append("> run_id: %s | substrate: %s | workers: %s/%s" % (
        meta.get("run_id", "?"), meta.get("substrate", "?"),
        meta.get("workers_eff", "?"), meta.get("workers_req", "?")))
    wall = "%dms" % meta["wall_ms"] if meta.get("wall_ms") else "?"
    base = "%dms" % meta["baseline_ms"] if meta.get("baseline_ms") else "n/a"
    L.append("> portions: %d | wall-clock: %s | serial baseline: %s%s" % (
        len(ledger_rows), wall, base, speed))
    L.append("> Generated by /pro.scan — claims carry provenance; verify before acting.")
    if capped:
        L.append(">")
        L.append("> NOTE: capped — %s" % capped)
    L.append("")
    if findings_md and findings_md.strip():
        L.append(findings_md.rstrip())
        L.append("")
    else:
        for sec in ("Architecture Map", "Module / Dependency Overview",
                    "Risk Hotspots", "Conflicts", "Unknowns"):
            L.append("## %s" % sec)
            L.append("_(pending merge — no findings supplied)_")
            L.append("")
    # Coverage Ledger — always last, always complete
    L.append("## Coverage Ledger")
    L.append("")
    L.append("| portion | files | status | reason |")
    L.append("|---|---|---|---|")
    for r in ledger_rows:
        L.append("| %s | %d | %s | %s |" % (r["portion"], r["files"], r["status"], r["reason"]))
    L.append("")
    return "\n".join(L)


def atomic_write(path, text):
    d = os.path.dirname(path) or "."
    os.makedirs(d, exist_ok=True)
    tmp = os.path.join(d, ".%s.tmp.%d" % (os.path.basename(path), os.getpid()))
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, path)  # atomic on POSIX


def with_lock(lock_path, fn, tries=50, wait=0.1):
    """Best-effort per-repo lock so two concurrent scans don't clobber latest.md."""
    os.makedirs(os.path.dirname(lock_path) or ".", exist_ok=True)
    acquired = False
    for _ in range(tries):
        try:
            fd = os.open(lock_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            os.write(fd, str(os.getpid()).encode())
            os.close(fd)
            acquired = True
            break
        except FileExistsError:
            time.sleep(wait)
    try:
        return fn()
    finally:
        if acquired:
            try:
                os.unlink(lock_path)
            except OSError:
                pass


def main():
    ap = argparse.ArgumentParser(description="Assemble the merged scan report + Coverage Ledger.")
    ap.add_argument("--portions", required=True)
    ap.add_argument("--results-dir", required=True)
    ap.add_argument("--out-dir", default=".knowledge/scan")
    ap.add_argument("--run-id", required=True)
    ap.add_argument("--substrate", default="?")
    ap.add_argument("--workers-eff", default="?")
    ap.add_argument("--workers-req", default="?")
    ap.add_argument("--repo", default="repository")
    ap.add_argument("--findings-md", default="")
    ap.add_argument("--wall-ms", type=int, default=0)
    ap.add_argument("--baseline-ms", type=int, default=0)
    ap.add_argument("--capped", default="")
    ap.add_argument("--no-archive", action="store_true")
    args = ap.parse_args()

    portions = load_portions(args.portions)
    rows, gaps = coverage_ledger(portions, args.results_dir)

    findings = ""
    if args.findings_md and os.path.isfile(args.findings_md):
        findings = open(args.findings_md, encoding="utf-8").read()

    meta = {"repo": args.repo, "run_id": args.run_id, "substrate": args.substrate,
            "workers_eff": args.workers_eff, "workers_req": args.workers_req,
            "wall_ms": args.wall_ms, "baseline_ms": args.baseline_ms}
    report = render(meta, findings, rows, args.capped)

    latest = os.path.join(args.out_dir, "latest.md")
    archive = os.path.join(args.out_dir, "%s.md" % args.run_id)

    def _write():
        atomic_write(latest, report)
        if not args.no_archive:
            atomic_write(archive, report)

    with_lock(os.path.join(args.out_dir, ".lock"), _write)

    sys.stderr.write("scan_report.py: wrote %s (%d portions, %d coverage gap(s))%s\n" % (
        latest, len(rows), gaps, "" if args.no_archive else " + archive"))
    # exit 0 always — gaps are reported in the ledger, not via exit code (no silent fail,
    # but a coverage gap is not itself a script failure).


if __name__ == "__main__":
    main()
